[package]
name = "serif-examples"
version = "0.1.0"
publish = false
edition = "2021"
default-run = "yak-shave"

[[bin]]
name = "yak-shave"
path = "yak_shave.rs"

[dependencies]
serif = { path = ".." }
thiserror = "2"
tracing = { version = "0.1", features = ["attributes"] }
